export const programmes = [
 {id:'network',code:'NET-101',title:'Networking Foundations',category:'Networking',level:'Foundation',weeks:4,capacity:24,taken:17,colour:'blue',description:'Build and troubleshoot a small office network. Work with IP addressing, switching and practical connectivity checks.',outcomes:['Plan an IPv4 addressing scheme','Configure a switched network','Verify and document connectivity'],assessment:'Small office network design',brief:'Describe a network for 20 staff across two departments. Include your subnet plan, switch configuration approach and the commands you would use to verify connectivity.',prerequisite:null,trainer:'Alex Morgan'},
 {id:'python',code:'DEV-102',title:'Python for IT Automation',category:'Development',level:'Foundation',weeks:5,capacity:20,taken:14,colour:'purple',description:'Turn repetitive support tasks into reliable Python scripts, from processing logs to validating user input.',outcomes:['Break a task into reusable functions','Validate input and handle errors','Test and document an automation script'],assessment:'Support log analyser',brief:'Write or describe a Python script that reads support logs, counts errors and produces a summary. Include input validation, error handling and three test cases.',prerequisite:null,trainer:'Alex Morgan'},
 {id:'security',code:'SEC-201',title:'Network Security Essentials',category:'Security',level:'Intermediate',weeks:6,capacity:18,taken:11,colour:'teal',description:'Apply firewall rules, identify common threats and protect a small business network.',outcomes:['Identify network threats','Design least-privilege firewall rules','Verify controls and report findings'],assessment:'Small business security review',brief:'Review a small business network. Identify three threats, propose firewall rules and describe how you would verify each control.',prerequisite:'network',trainer:'Alex Morgan'},
 {id:'cloud',code:'CLD-201',title:'Cloud Infrastructure',category:'Cloud',level:'Intermediate',weeks:6,capacity:16,taken:16,colour:'orange',description:'Plan a cloud environment with sensible network, access and recovery decisions.',outcomes:['Plan cloud resources','Apply access controls','Design a recovery approach'],assessment:'Cloud deployment plan',brief:'Design a small cloud deployment, including access controls and recovery.',prerequisite:null,trainer:'Alex Morgan'},
 {id:'sql',code:'DB-103',title:'Practical SQL & Databases',category:'Development',level:'Foundation',weeks:4,capacity:22,taken:13,colour:'pink',description:'Design relational tables and write clear queries that answer real business questions.',outcomes:['Design related tables','Write filtering and join queries','Verify data integrity'],assessment:'Service desk database',brief:'Design tables for users, tickets and technicians. Give three SQL queries and explain how keys prevent inconsistent records.',prerequisite:null,trainer:'Alex Morgan'},
 {id:'support',code:'IT-100',title:'IT Support Essentials',category:'Support',level:'Foundation',weeks:3,capacity:24,taken:12,colour:'green',description:'Practise a structured approach to diagnosing faults, supporting users and documenting solutions.',outcomes:['Diagnose a reported issue','Explain a practical solution','Record and verify the resolution'],assessment:'Help desk incident response',brief:'A user cannot access a shared folder. Describe your diagnostic steps, communication with the user and the evidence you would record when closing the ticket.',prerequisite:null,trainer:'Alex Morgan'},
] as const;
export const rubric=[{name:'Planning & understanding',max:20,min:16},{name:'Technical solution',max:40,min:32},{name:'Verification & documentation',max:40,min:32}];
export function outcome(scores:number[]){return scores.every((n,i)=>n>=rubric[i].min);}
export function validateScores(value:unknown):number[]{if(!Array.isArray(value)||value.length!==3||value.some((n,i)=>typeof n!=='number'||!Number.isFinite(n)||n<0||n>rubric[i].max))throw new Error('Enter three scores within the permitted ranges.');return value;}
export const sampleSubmission='I divided the office into two /27 subnets: 192.168.10.0/27 and 192.168.10.32/27. Each subnet supports 30 usable host addresses. I would create a VLAN for each department and assign switch access ports to the relevant VLAN. A router or Layer 3 switch provides inter-VLAN routing.\n\nI would verify the port and VLAN configuration with show vlan brief and show interfaces status, then check host addressing with ipconfig. Ping tests within each VLAN and across the gateway confirm reachability. Finally, I would document the address allocation, port map and test results, including any failed tests and fixes.';
